version: '2'
services:
  elasticsearch:
    image: elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: logstash:5
    command: -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash.d:/etc/logstash/conf.d
      - ./demo_project.log:/tmp/demo_project.log
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
      - "5001:5001"
  kibana:
    image: kibana:5
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
